[package]
name = "fern"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0
debug = "full"

[dependencies]
env_logger = "0.11.6"
fern-web = { version = "0.1.0", path = "./crates/fern-web" }
log = "0.4.25"
tokio = { version = "1.43.0", features = ["full"] }
